### ISSUE TITLE
Module 'SWXMLHash' has no member named 'parse'

### ISSUE THREAD

**Issue by Babyyoda777** [BasamAlasaly/Swift-XML-RSS-Reader-iOS15.0#1]
Followed instructions, tried resetting package cache, nothing worked :/

**Comment by BasamAlasaly** [comment]
> Followed instructions, tried resetting package cache, nothing worked :/ 

Hey! SWXMLHash has been renamed to "XMLHash"

Try _XMLHash.parse(_ instead

and it should work!

Sorry about that, but thank you for pointing it out. Will make sure to update the repo 👍

**Comment by Babyyoda777** [comment]
> > Followed instructions, tried resetting package cache, nothing worked :/ 
> 
> Hey! SWXMLHash has been renamed to "XMLHash"
> 
> Try _XMLHash.parse(_ instead
> 
> and it should work!
> 
> Sorry about that, but thank you for pointing it out. Will make sure to update the repo 👍

Oh thanks that worked!
